#!/bin/bash

PIDFILE=$1

if [ ! -f $PIDFILE ]; then
  echo "UNKNOWN: ${PIDFILE} does not exist"
  exit 3
fi

PID=`cat $PIDFILE`
kill -0 $PID
RESULT=$?

if [[ "${RESULT}" = "0" ]]; then
  echo "OK: Process ID ${PID} is running"
  exit 0
else
  echo "CRITICAL: Process ID ${PID} is NOT running"
  exit 2
fi
