#!/usr/bin/env python

from __future__ import print_function

import argparse
import socket
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--socket', help="Socket to connect to", type=str,
                    default="/var/run/pdns.controlsocket")
parser.add_argument('--timeout', help="Socket timeout", type=int, default=5)
args = parser.parse_args()

s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
s.settimeout(args.timeout)

try:
    s.connect(args.socket)
    s.send('PING\n')
    data = s.recv(1024)
except socket.timeout:
    print ("CRITICAL: Socket timeout, please investigate!")
    sys.exit(2)
except socket.error, e:
    print ("CRITICAL: %s" % e)
    sys.exit(2)

s.close()

if data != 'PONG':
    print('CRITICAL: Ping error, didn\' receive PONG!')
    sys.exit(2)
else:
    print("OK: Socket is responding with PONG")
    sys.exit(0)